// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AI action that originated a thread (FEATURES 6.5.3).
enum AiActionType { translate, explain, search, chat, vision }

/// BYOK AI configuration (FEATURES 6.1). Stored in the `settings` table;
/// API keys never leave the local machine (FEATURES 9.2.2).
///
/// `#[serde(default)]`: JSON stored by older builds may lack newer fields.
/// Without it, a missing non-Option field (e.g. `search_use_builtin`) fails
/// the whole read and the UI would show an empty config.
class AiConfig {
  /// Base URL for the text model (OpenAI-compatible).
  final String baseUrl;
  final String apiKey;
  final String textModel;
  final String visionModel;

  /// Optional independent vision config; falls back to the above when empty (6.1.2).
  final String? visionBaseUrl;
  final String? visionApiKey;

  /// Web-search provider config (6.1.4): two modes -- built-in search via
  /// the Responses API (`search_use_builtin`, DeepSeek web_search tool,
  /// reuses the text config) or a third-party Bocha-compatible endpoint.
  /// Empty `search_base_url` uses the Bocha default; empty `search_api_key`
  /// disables real web search.
  final bool searchUseBuiltin;
  final String? searchBaseUrl;
  final String? searchApiKey;

  /// Translation target language, default "中文" (6.1.3).
  final String translateTargetLang;

  /// Web search toggle (6.1.4).
  final bool webSearchEnabled;

  /// Full-page OCR model set (7.1.9): "high_precision" (server models,
  /// accuracy first) or "fast" (mobile models, speed / size). Field-level
  /// default so configs saved by older builds read a valid value.
  final String ocrMode;

  /// Carry the book's full conversation history on every request
  /// (default: the window history -- 追问 always sends the thread's turns
  /// from the start; off = every turn is answered independently).
  final bool includeBookHistory;

  /// Thinking mode (reasoning models): the request carries
  /// `reasoning_effort` per the official API docs when enabled.
  final bool enableReasoning;

  /// Reasoning level when [enable_reasoning]: "low" | "medium" | "high".
  final String reasoningEffort;

  /// Sampling temperature for text replies (0.0-2.0, OpenAI range).
  final double temperature;

  /// Role template for text replies: "general" | "academic" | "novel" |
  /// "tech" | "language" | "custom" (the role segment is prepended to the
  /// per-action system prompt).
  final String promptTemplate;

  /// User-written role prompt when [prompt_template] is "custom".
  final String customPrompt;

  /// The user's saved custom prompt templates (设置 → AI 回复 → 自定义):
  /// named entries persist here; selecting one copies its text into
  /// [custom_prompt] at save time.
  final List<CustomPrompt> customPrompts;

  /// User edits of the built-in role templates: template id -> the
  /// user's text. A present entry replaces the built-in prompt (设置 →
  /// AI 回复: selecting a template shows its text, editable).
  final Map<String, String> templateOverrides;

  const AiConfig({
    required this.baseUrl,
    required this.apiKey,
    required this.textModel,
    required this.visionModel,
    this.visionBaseUrl,
    this.visionApiKey,
    required this.searchUseBuiltin,
    this.searchBaseUrl,
    this.searchApiKey,
    required this.translateTargetLang,
    required this.webSearchEnabled,
    required this.ocrMode,
    required this.includeBookHistory,
    required this.enableReasoning,
    required this.reasoningEffort,
    required this.temperature,
    required this.promptTemplate,
    required this.customPrompt,
    required this.customPrompts,
    required this.templateOverrides,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      apiKey.hashCode ^
      textModel.hashCode ^
      visionModel.hashCode ^
      visionBaseUrl.hashCode ^
      visionApiKey.hashCode ^
      searchUseBuiltin.hashCode ^
      searchBaseUrl.hashCode ^
      searchApiKey.hashCode ^
      translateTargetLang.hashCode ^
      webSearchEnabled.hashCode ^
      ocrMode.hashCode ^
      includeBookHistory.hashCode ^
      enableReasoning.hashCode ^
      reasoningEffort.hashCode ^
      temperature.hashCode ^
      promptTemplate.hashCode ^
      customPrompt.hashCode ^
      customPrompts.hashCode ^
      templateOverrides.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiConfig &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          textModel == other.textModel &&
          visionModel == other.visionModel &&
          visionBaseUrl == other.visionBaseUrl &&
          visionApiKey == other.visionApiKey &&
          searchUseBuiltin == other.searchUseBuiltin &&
          searchBaseUrl == other.searchBaseUrl &&
          searchApiKey == other.searchApiKey &&
          translateTargetLang == other.translateTargetLang &&
          webSearchEnabled == other.webSearchEnabled &&
          ocrMode == other.ocrMode &&
          includeBookHistory == other.includeBookHistory &&
          enableReasoning == other.enableReasoning &&
          reasoningEffort == other.reasoningEffort &&
          temperature == other.temperature &&
          promptTemplate == other.promptTemplate &&
          customPrompt == other.customPrompt &&
          customPrompts == other.customPrompts &&
          templateOverrides == other.templateOverrides;
}

/// A single message in a thread (table: ai_messages).
class AiMessage {
  final PlatformInt64 id;
  final PlatformInt64 threadId;
  final AiRole role;

  /// Markdown content (rendered with flutter_markdown + LaTeX on the Dart side).
  final String content;

  /// Vision screenshot file (relative to the app data dir), when this
  /// message carried a 区域识图 capture (v4, FEATURES 6.6.2).
  final String? imagePath;
  final String createdAt;

  const AiMessage({
    required this.id,
    required this.threadId,
    required this.role,
    required this.content,
    this.imagePath,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      threadId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      imagePath.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          threadId == other.threadId &&
          role == other.role &&
          content == other.content &&
          imagePath == other.imagePath &&
          createdAt == other.createdAt;
}

/// Chat message role (OpenAI-compatible).
enum AiRole { user, assistant, system }

/// A persisted AI conversation window (table: ai_threads). One window per
/// book (FEATURES 6.5.4): every AI exchange inside a book shares its window;
/// `book_id` is null for conversations started without an open book.
class AiThread {
  final PlatformInt64 id;

  /// Window title: the book title snapshot (or "未打开书籍" without one).
  final String title;

  /// Latest action performed in the window (icon in the history list).
  final AiActionType actionType;

  /// The book this window belongs to; null = no-book window. No FK: the
  /// conversation survives book deletion (deletion is a user choice).
  final PlatformInt64? bookId;
  final String createdAt;
  final String updatedAt;

  const AiThread({
    required this.id,
    required this.title,
    required this.actionType,
    this.bookId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      actionType.hashCode ^
      bookId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiThread &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          actionType == other.actionType &&
          bookId == other.bookId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// One user-saved custom prompt template (name + text).
class CustomPrompt {
  final String name;
  final String text;

  const CustomPrompt({required this.name, required this.text});

  @override
  int get hashCode => name.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomPrompt &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          text == other.text;
}
