// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A normalized rectangle on a page: all values in [0.0, 1.0].
class NormRect {
  final double x;
  final double y;
  final double w;
  final double h;

  const NormRect({
    required this.x,
    required this.y,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ w.hashCode ^ h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NormRect &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h;
}

/// A text-layer annotation (highlight / underline / strikethrough / note).
/// `rects` holds one normalized rect per selected line (FEATURES 4.3.1/4.3.2);
/// `text` is the selected text the mark was created from (sidebar display +
/// Markdown export, FEATURES 4.5.1/4.5.2).
class TextAnnotation {
  final PlatformInt64 id;
  final PlatformInt64 bookId;
  final PlatformInt64 page;
  final TextAnnotationKind kind;

  /// Selected text the annotation was created from; None for legacy rows
  /// created before the column existed.
  final String? text;

  /// Note text; None for mark-only annotations.
  final String? content;

  /// One rect per line of the selection.
  final List<NormRect> rects;
  final String? color;
  final String createdAt;
  final String updatedAt;

  const TextAnnotation({
    required this.id,
    required this.bookId,
    required this.page,
    required this.kind,
    this.text,
    this.content,
    required this.rects,
    this.color,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      page.hashCode ^
      kind.hashCode ^
      text.hashCode ^
      content.hashCode ^
      rects.hashCode ^
      color.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextAnnotation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          page == other.page &&
          kind == other.kind &&
          text == other.text &&
          content == other.content &&
          rects == other.rects &&
          color == other.color &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Text annotation kind (FEATURES 4.3).
enum TextAnnotationKind { highlight, underline, strikethrough, note }
