// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A library entry. Maps to the `books` table.
class Book {
  final PlatformInt64 id;
  final String title;

  /// Original filesystem path -- de-dup key (FEATURES 2.1).
  final String originalPath;

  /// Path of the copy inside the app data directory.
  final String storedPath;
  final BookType fileType;
  final PlatformInt64 pageCount;

  /// Thumbnail path, nullable (FEATURES 2.6).
  final String? coverPath;
  final bool favorite;
  final PlatformInt64? categoryId;

  /// ISO-8601, nullable until first open.
  final String? lastOpenedAt;
  final String importedAt;

  const Book({
    required this.id,
    required this.title,
    required this.originalPath,
    required this.storedPath,
    required this.fileType,
    required this.pageCount,
    this.coverPath,
    required this.favorite,
    this.categoryId,
    this.lastOpenedAt,
    required this.importedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      originalPath.hashCode ^
      storedPath.hashCode ^
      fileType.hashCode ^
      pageCount.hashCode ^
      coverPath.hashCode ^
      favorite.hashCode ^
      categoryId.hashCode ^
      lastOpenedAt.hashCode ^
      importedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Book &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          originalPath == other.originalPath &&
          storedPath == other.storedPath &&
          fileType == other.fileType &&
          pageCount == other.pageCount &&
          coverPath == other.coverPath &&
          favorite == other.favorite &&
          categoryId == other.categoryId &&
          lastOpenedAt == other.lastOpenedAt &&
          importedAt == other.importedAt;
}

/// Document type (FEATURES 1.2). Determines text-layer acquisition strategy.
enum BookType {
  /// Text-layer PDF -- pdfjs native text, no OCR.
  pdf,

  /// Image file (PNG/JPG/WEBP/BMP/GIF/TIFF) -- treated like a scanned page.
  image,
}

/// A custom book classification (FEATURES 2.8 / 9.1.9).
class Category {
  final PlatformInt64 id;
  final String name;
  final PlatformInt64 sortOrder;
  final String createdAt;

  const Category({
    required this.id,
    required this.name,
    required this.sortOrder,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ sortOrder.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt;
}
