// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Persisted reading position for a book.
class ReadingProgress {
  final PlatformInt64 bookId;
  final PlatformInt64 page;

  /// Zoom factor, default 1.2 = 120% (FEATURES 3.2.1).
  final double zoom;
  final ViewMode viewMode;
  final String updatedAt;

  const ReadingProgress({
    required this.bookId,
    required this.page,
    required this.zoom,
    required this.viewMode,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      page.hashCode ^
      zoom.hashCode ^
      viewMode.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingProgress &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          page == other.page &&
          zoom == other.zoom &&
          viewMode == other.viewMode &&
          updatedAt == other.updatedAt;
}

/// Reader view mode (FEATURES 3.1).
enum ViewMode {
  /// Single page, continuous scroll (3.1.1).
  single,

  /// Two pages side by side, row height = max of the pair, vertical scroll (3.1.2).
  doubleScroll,

  /// Two-page flip mode, no scrollbar, centered pair, step 2 (3.1.3).
  doublePage,
}
