// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'annotation.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A formula region detected from font metadata (plan §3.4): the rect on the
/// original page, the captured image (PNG under `translated/{book_id}/
/// formulas/`, may be absent when capture failed) and the placeholder token
/// that substitutes the formula text during translation.
class FormulaRegion {
  /// Normalized rect (top-left origin, Flutter space), same convention as
  /// annotation rects.
  final NormRect rect;

  /// Absolute path of the captured region image (PNG under
  /// `{data_dir}/translated/{book_id}/formulas/`, empty when capture
  /// failed). Stored absolute so the Flutter pane + PDF writer can read it
  /// without resolving the app data dir.
  final String? imagePath;

  /// The raw formula text as it appeared on the page.
  final String sourceText;

  /// Placeholder token substituted for the formula during translation
  /// (random-prefixed, plan §4.3; e.g. `⟨F3a9-MATH_0⟩`). The translated
  /// text keeps the token; consumers substitute it with the original text
  /// (pane) or the embedded image (PDF).
  final String placeholder;

  const FormulaRegion({
    required this.rect,
    this.imagePath,
    required this.sourceText,
    required this.placeholder,
  });

  @override
  int get hashCode =>
      rect.hashCode ^
      imagePath.hashCode ^
      sourceText.hashCode ^
      placeholder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormulaRegion &&
          runtimeType == other.runtimeType &&
          rect == other.rect &&
          imagePath == other.imagePath &&
          sourceText == other.sourceText &&
          placeholder == other.placeholder;
}

/// One glossary entry (table: `translation_glossary`, plan §4.4): a fixed
/// term pair applied to every translation for consistent naming.
class GlossaryEntry {
  final PlatformInt64 id;
  final String sourceTerm;
  final String targetTerm;

  /// Optional language pair restriction (DeepL glossaries are per pair);
  /// null = applies everywhere.
  final String? sourceLang;
  final String? targetLang;

  const GlossaryEntry({
    required this.id,
    required this.sourceTerm,
    required this.targetTerm,
    this.sourceLang,
    this.targetLang,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceTerm.hashCode ^
      targetTerm.hashCode ^
      sourceLang.hashCode ^
      targetLang.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossaryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceTerm == other.sourceTerm &&
          targetTerm == other.targetTerm &&
          sourceLang == other.sourceLang &&
          targetLang == other.targetLang;
}

/// The cached translation of one page (table: `page_translation_cache`).
/// The cache key is (book_id, page, target_lang, provider); `source_hash`
/// guards freshness (a re-extracted page that changed invalidates the row).
class PageTranslation {
  /// 1-indexed page number (plan §2: absolute page number, never reorder).
  final PlatformInt64 page;
  final String targetLang;

  /// Provider id string (`deepl` / `openai_compat` / `reuse_ai`).
  final String provider;

  /// SHA-256 of the page's paragraph texts at translation time.
  final String sourceHash;
  final List<TranslatedParagraph> paragraphs;

  /// Fraction of translatable paragraphs (text kind, noise/formula
  /// excluded) with a non-empty translation (plan §4.7).
  final double coverage;

  const PageTranslation({
    required this.page,
    required this.targetLang,
    required this.provider,
    required this.sourceHash,
    required this.paragraphs,
    required this.coverage,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      targetLang.hashCode ^
      provider.hashCode ^
      sourceHash.hashCode ^
      paragraphs.hashCode ^
      coverage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageTranslation &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          targetLang == other.targetLang &&
          provider == other.provider &&
          sourceHash == other.sourceHash &&
          paragraphs == other.paragraphs &&
          coverage == other.coverage;
}

/// One reconstructed paragraph of a page (plan §3): text + line rects +
/// formula regions found inside it.
class Paragraph {
  final String text;

  /// Bounding rects of the paragraph's lines (normalized).
  final List<NormRect> rects;

  /// 1-indexed page number.
  final PlatformInt64 page;
  final ParagraphKind kind;

  /// 1.0 for text-layer paragraphs; the minimum OCR line confidence
  /// otherwise.
  final double confidence;
  final List<FormulaRegion> formulaRegions;

  const Paragraph({
    required this.text,
    required this.rects,
    required this.page,
    required this.kind,
    required this.confidence,
    required this.formulaRegions,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      rects.hashCode ^
      page.hashCode ^
      kind.hashCode ^
      confidence.hashCode ^
      formulaRegions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Paragraph &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          rects == other.rects &&
          page == other.page &&
          kind == other.kind &&
          confidence == other.confidence &&
          formulaRegions == other.formulaRegions;
}

/// What a paragraph is (plan §3): normal text, a whole-paragraph formula
/// (kept as an image, never machine-translated), or removed noise
/// (header / footer / page number).
enum ParagraphKind { text, formula, noise }

/// Per-paragraph translation status in the pane (plan §5).
enum ParagraphStatus {
  pending,
  translating,
  done,

  /// OCR confidence < 0.8 (plan §3.5): shown with a "请核对" hint.
  lowConfidence,
  failed,

  /// Placeholder backfill validation failed: the formula may be wrong.
  formulaCheck,
}

/// A paragraph with its translation (plan §4-5). `translated` still contains
/// the formula placeholder tokens: the pane substitutes them with
/// [FormulaRegion::source_text], the PDF writer with the captured image.
class TranslatedParagraph {
  final String source;

  /// Machine translation with `⟨..MATH_n⟩` tokens still in place (may be
  /// empty for whole-paragraph formulas, which are kept as images).
  final String translated;
  final ParagraphKind kind;
  final ParagraphStatus status;
  final double confidence;
  final List<FormulaRegion> formulaRegions;

  const TranslatedParagraph({
    required this.source,
    required this.translated,
    required this.kind,
    required this.status,
    required this.confidence,
    required this.formulaRegions,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      translated.hashCode ^
      kind.hashCode ^
      status.hashCode ^
      confidence.hashCode ^
      formulaRegions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslatedParagraph &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          translated == other.translated &&
          kind == other.kind &&
          status == other.status &&
          confidence == other.confidence &&
          formulaRegions == other.formulaRegions;
}

/// What happens to a running whole-book translation when the user switches
/// books / closes the pane (plan §8, user decision). `Ask` is the default
/// until the user picks a behaviour in the first-run dialog.
enum TranslationBackgroundBehavior {
  ask,

  /// Keep translating in the background (switching books does not cancel).
  continue_,

  /// Pause on book switch, resume automatically when the book reopens.
  pauseResume,

  /// Cancel as soon as the user leaves the book / closes the pane.
  cancel,
}

/// 对照阅读 configuration (plan §8). Stored in the `settings` table under the
/// key `translation_config` as one JSON value. The **target language is NOT
/// configured here** (v4.2 user decision): it is shared with the AI settings'
/// `AiConfig.translate_target_lang`.
///
/// `#[serde(default)]`: the whole config is one JSON blob; fields added by
/// newer builds must default cleanly when older JSON is read (mirrors
/// [super::ai::AiConfig]).
class TranslationConfig {
  /// Translation service (DeepL / generic OpenAI-compatible / reuse AI).
  final TranslationProviderKind provider;

  /// DeepL / OpenAI-compatible endpoint override. Empty = DeepL picks the
  /// free/pro endpoint from the key (":fx" suffix), OpenAI-compat requires
  /// an explicit base URL.
  final String? baseUrl;
  final String? apiKey;

  /// Model name (OpenAI-compatible / reuse-AI override). Empty = the AI
  /// settings' text model.
  final String? model;

  /// Source language: "auto" (default) or a specific language name / code.
  final String sourceLang;

  /// When pages are translated (plan §10). Default 随进度.
  final TranslationMode mode;

  /// Whole-book background behaviour (plan §10), default `Ask`.
  final TranslationBackgroundBehavior backgroundBehavior;

  /// Auto-OCR scanned pages (no text layer) before translating (plan §3.5).
  final bool autoOcr;

  /// Concurrent page translations for whole-book mode (1-8).
  final PlatformInt64 concurrency;

  /// Translation cache budget in MB (plan §7, default 2GB).
  final PlatformInt64 cacheLimitMb;

  const TranslationConfig({
    required this.provider,
    this.baseUrl,
    this.apiKey,
    this.model,
    required this.sourceLang,
    required this.mode,
    required this.backgroundBehavior,
    required this.autoOcr,
    required this.concurrency,
    required this.cacheLimitMb,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      sourceLang.hashCode ^
      mode.hashCode ^
      backgroundBehavior.hashCode ^
      autoOcr.hashCode ^
      concurrency.hashCode ^
      cacheLimitMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          sourceLang == other.sourceLang &&
          mode == other.mode &&
          backgroundBehavior == other.backgroundBehavior &&
          autoOcr == other.autoOcr &&
          concurrency == other.concurrency &&
          cacheLimitMb == other.cacheLimitMb;
}

/// When pages get translated (plan §10). Default: translate the visible page
/// plus the next two as the user reads (随进度).
enum TranslationMode { wholeBook, withProgress, manual }

/// One progress event of a `translate_page` / `build_translated_pdf` stream.
class TranslationProgressEvent {
  /// 1-indexed page the event belongs to.
  final PlatformInt64 page;

  /// Paragraphs finished on the page (0 for build events, which are
  /// page-granular).
  final PlatformInt64 doneParagraphs;
  final PlatformInt64 totalParagraphs;

  /// Page coverage fraction (translate events).
  final double coverage;

  /// Whether the stream has completed (page done / whole build done).
  final bool finished;
  final String? error;

  const TranslationProgressEvent({
    required this.page,
    required this.doneParagraphs,
    required this.totalParagraphs,
    required this.coverage,
    required this.finished,
    this.error,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      doneParagraphs.hashCode ^
      totalParagraphs.hashCode ^
      coverage.hashCode ^
      finished.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationProgressEvent &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          doneParagraphs == other.doneParagraphs &&
          totalParagraphs == other.totalParagraphs &&
          coverage == other.coverage &&
          finished == other.finished &&
          error == other.error;
}

/// Translation service selection (plan §8). `ReuseAi` reuses the AI settings'
/// OpenAI-compatible config for LLM translation.
enum TranslationProviderKind { deepL, openAiCompat, reuseAi }
