// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One glossary entry (table: `translation_glossary`, plan §4.4): a fixed
/// term pair applied to every translation for consistent naming.
class GlossaryEntry {
  final PlatformInt64 id;
  final String sourceTerm;
  final String targetTerm;

  /// Optional language pair restriction (DeepL glossaries are per pair);
  /// null = applies everywhere.
  final String? sourceLang;
  final String? targetLang;

  const GlossaryEntry({
    required this.id,
    required this.sourceTerm,
    required this.targetTerm,
    this.sourceLang,
    this.targetLang,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceTerm.hashCode ^
      targetTerm.hashCode ^
      sourceLang.hashCode ^
      targetLang.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossaryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceTerm == other.sourceTerm &&
          targetTerm == other.targetTerm &&
          sourceLang == other.sourceLang &&
          targetLang == other.targetLang;
}

/// What happens to a running whole-book translation when the user switches
/// books / closes the pane (plan §8, user decision). `Ask` is the default
/// until the user picks a behaviour in the first-run dialog.
enum TranslationBackgroundBehavior {
  ask,

  /// Keep translating in the background (switching books does not cancel).
  continue_,

  /// Pause on book switch, resume automatically when the book reopens.
  pauseResume,

  /// Cancel as soon as the user leaves the book / closes the pane.
  cancel,
}

/// 对照阅读 configuration (plan §8). Stored in the `settings` table under the
/// key `translation_config` as one JSON value. The **target language is NOT
/// configured here** (v4.2 user decision): it is shared with the AI settings'
/// `AiConfig.translate_target_lang`.
///
/// `#[serde(default)]`: the whole config is one JSON blob; fields added by
/// newer builds must default cleanly when older JSON is read (mirrors
/// [super::ai::AiConfig]).
class TranslationConfig {
  /// Translation service (DeepL / generic OpenAI-compatible / reuse AI).
  final TranslationProviderKind provider;

  /// DeepL / OpenAI-compatible endpoint override. Empty = DeepL picks the
  /// free/pro endpoint from the key (":fx" suffix), OpenAI-compat requires
  /// an explicit base URL.
  final String? baseUrl;
  final String? apiKey;

  /// Model name (OpenAI-compatible / reuse-AI override). Empty = the AI
  /// settings' text model.
  final String? model;

  /// Source language: "auto" (default) or a specific language name / code.
  final String sourceLang;

  /// When pages are translated (plan §10). Default 随进度.
  final TranslationMode mode;

  /// Whole-book background behaviour (plan §10), default `Ask`.
  final TranslationBackgroundBehavior backgroundBehavior;

  /// Auto-OCR scanned pages (no text layer) before translating (plan §3.5).
  final bool autoOcr;

  /// Concurrent page translations for whole-book mode (1-8).
  final PlatformInt64 concurrency;

  /// Translation cache budget in MB (plan §7, default 2GB).
  final PlatformInt64 cacheLimitMb;

  const TranslationConfig({
    required this.provider,
    this.baseUrl,
    this.apiKey,
    this.model,
    required this.sourceLang,
    required this.mode,
    required this.backgroundBehavior,
    required this.autoOcr,
    required this.concurrency,
    required this.cacheLimitMb,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      sourceLang.hashCode ^
      mode.hashCode ^
      backgroundBehavior.hashCode ^
      autoOcr.hashCode ^
      concurrency.hashCode ^
      cacheLimitMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          sourceLang == other.sourceLang &&
          mode == other.mode &&
          backgroundBehavior == other.backgroundBehavior &&
          autoOcr == other.autoOcr &&
          concurrency == other.concurrency &&
          cacheLimitMb == other.cacheLimitMb;
}

/// When pages get translated (plan §10). Default: translate the visible page
/// plus the next two as the user reads (随进度).
enum TranslationMode { wholeBook, withProgress, manual }

/// Translation service selection (plan §8). `ReuseAi` reuses the AI settings'
/// OpenAI-compatible config for LLM translation.
enum TranslationProviderKind { deepL, openAiCompat, reuseAi }
