// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models/ai.dart';
import 'models/annotation.dart';
import 'models/book.dart';
import 'models/progress.dart';
import 'models/translate.dart';
import 'ocr.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pdf/types.dart';

// These functions are ignored because they are not marked as `pub`: `ai_client`, `builtin_search_stream`, `current_bitmap`, `current_boxes`, `current_page_has_text`, `current_thumbnail`, `drain_stream`, `ensure_api_key`, `err`, `import_book_inner`, `index_ocr_result`, `init_result`, `ok`, `open_error`, `page_render_result`, `rebuild_cover_file`, `resolve_ai_image_path`, `save_ai_image`, `save_cover_thumbnail`, `save_rgba_as_png`, `search_system_prompt`, `system_message`, `system_prompt_for`, `try_init_at`, `try_init`, `wrap_input`, `wrap_untrusted_input`

/// Crate version, surfaced in the About / settings UI.
Future<String> appVersion() => RustLib.instance.api.crateApiAppVersion();

/// Initialize the Rust core. Called exactly once on app startup, before any
/// other command. Opens SQLite, applies the schema (idempotent), and sets up
/// tracing. Safe to call again; returns the cached result.
Future<InitResult> initCore() => RustLib.instance.api.crateApiInitCore();

/// Test hook: initialize the core against an explicit database path so
/// integration tests never touch the user's real data (all test writes --
/// books, annotations, AI config -- land in the isolated DB). Mirrors
/// [init_core] otherwise. Not used in production.
Future<InitResult> initCoreWithDbPath({required String dbPath}) =>
    RustLib.instance.api.crateApiInitCoreWithDbPath(dbPath: dbPath);

/// Read a setting value by key (skeleton: direct KV read).
/// Returns empty string if the key is absent. Real subsystem repos wrap
/// this in M1; for the skeleton an empty string sentinel is sufficient.
///
/// # Panics
/// Panics if called before `init_core()` (programming error).
Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiGetSetting(key: key);

/// Write a setting value by key (upsert). Skeleton helper for theme etc.
/// Returns 1 on success, 0 on failure.
///
/// # Panics
/// Panics if called before `init_core()` (programming error).
Future<int> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, value: value);

/// List every book in the library, most-recently-opened first (FEATURES 2.2/2.3).
/// Returns an empty vec on error (the UI shows the empty-state guide).
Future<List<Book>> listBooks() => RustLib.instance.api.crateApiListBooks();

/// Fetch a single book by id. Returns `None` if not found (FEATURES 2.3:
/// the reader needs the book's stored_path and page_count to open it).
Future<Book?> getBook({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiGetBook(id: id);

/// Rebuild covers whose file is missing (FEATURES 2.6). Returns the number
/// of covers restored. PDF books whose `covers/{id}.png` disappeared are
/// re-rendered from their stored copy through an independent pdfium document;
/// image books already use the stored file itself, so they need nothing.
///
/// Called by the library screen after loading, so a lost cover heals without
/// the user having to open each book (and without any user-visible action).
Future<int> repairCovers() => RustLib.instance.api.crateApiRepairCovers();

/// Import a single file into the library (FEATURES 2.1).
///
/// Steps: validate path → infer type → de-dup by `original_path` → copy file
/// into `~/.local/share/RBWA/documents/` → insert row. The DB lock is released
/// during the file copy so concurrent reads are not blocked.
///
/// Async: pdfium open + cover rendering are heavyweight; running them off the
/// UI thread (FRB executes `async fn` on a worker) keeps the UI responsive.
Future<ImportResult> importBook({required String path}) =>
    RustLib.instance.api.crateApiImportBook(path: path);

/// Delete a book by id (FEATURES 2.4). Removes the row (cascading to progress,
/// annotations, OCR cache, text index via FK) and deletes the stored file
/// and cover thumbnail. Returns 1 on success, 0 if the book was not found.
Future<int> deleteBook({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteBook(id: id);

/// Toggle the favorite flag on a book (FEATURES 2.5). Returns the updated
/// book, or `None` if the id was not found.
Future<Book?> toggleFavorite({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiToggleFavorite(id: id);

/// Record that a book was opened (FEATURES 2.3: recent-open sort).
/// Returns 1 on success, 0 if the book was not found.
Future<int> touchLastOpened({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTouchLastOpened(id: id);

/// Assign a book to a category, or unclassify it (`category_id = None`)
/// (FEATURES 2.8). Returns 1 on success, 0 if the book was not found.
Future<int> assignCategory({
  required PlatformInt64 bookId,
  PlatformInt64? categoryId,
}) => RustLib.instance.api.crateApiAssignCategory(
  bookId: bookId,
  categoryId: categoryId,
);

/// List all categories (FEATURES 2.8). Empty vec on error.
Future<List<Category>> listCategories() =>
    RustLib.instance.api.crateApiListCategories();

/// Create a new category (FEATURES 2.8). Returns the new category, or `None`
/// if the name is already taken or creation failed.
Future<Category?> createCategory({required String name}) =>
    RustLib.instance.api.crateApiCreateCategory(name: name);

/// Rename a category (FEATURES 2.8). Returns 1 on success, 0 if not found or
/// the new name collides.
Future<int> renameCategory({required PlatformInt64 id, required String name}) =>
    RustLib.instance.api.crateApiRenameCategory(id: id, name: name);

/// Delete a category (FEATURES 2.8). Books referencing it fall back to
/// unclassified (`category_id` set to NULL via the FK rule). Returns 1 on
/// success, 0 if not found.
Future<int> deleteCategory({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteCategory(id: id);

/// Open a book's document for reading. Image books (PNG / JPG / WEBP) decode
/// via the `image` crate; PDFs open via pdfium. Must precede render/outline
/// calls (FEATURES 3.3). The document stays open until another book is
/// opened or `close_book` is called.
///
/// Async: document open is heavyweight and must not block the UI.
Future<OpenBookResult> openBook({required String storedPath}) =>
    RustLib.instance.api.crateApiOpenBook(storedPath: storedPath);

/// Close the currently-open document, freeing its memory.
Future<void> closeBook() => RustLib.instance.api.crateApiCloseBook();

/// Render a page (0-indexed) to an RGBA bitmap (FEATURES 3.6.2 / 7.3).
/// `zoom` is the user zoom factor (1.0 = 100%); `dpi_scale` is the device
/// pixel ratio for high-DPI rendering. Image books render through the same
/// pipeline (their single page scales with zoom).
///
/// Async: rendering is heavyweight and must not block the UI.
Future<PageRenderResult> renderPage({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required double zoom,
  required double dpiScale,
}) => RustLib.instance.api.crateApiRenderPage(
  bookId: bookId,
  page: page,
  zoom: zoom,
  dpiScale: dpiScale,
);

/// Render a small thumbnail for the sidebar (FEATURES 3.4.1 / 7.3).
///
/// Async: rendering is heavyweight and must not block the UI.
Future<PageRenderResult> renderThumbnail({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required int maxSize,
}) => RustLib.instance.api.crateApiRenderThumbnail(
  bookId: bookId,
  page: page,
  maxSize: maxSize,
);

/// Fetch the document outline (FEATURES 3.4.2).
///
/// Async: pdfium bookmark traversal can be slow on large documents.
Future<OutlineResult> getOutline({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiGetOutline(bookId: bookId);

/// Load the saved reading position for a book. Returns `None` on first open.
Future<ReadingProgress?> getProgress({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiGetProgress(bookId: bookId);

/// Save the reading position (upsert). `view_mode` is the string form
/// ("single" / "double_scroll" / "double_page"). Returns 1 on success.
Future<int> saveProgress({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required double zoom,
  required String viewMode,
}) => RustLib.instance.api.crateApiSaveProgress(
  bookId: bookId,
  page: page,
  zoom: zoom,
  viewMode: viewMode,
);

/// Extract per-character boxes for a page (0-indexed), normalized to [0,1]
/// with a top-left origin (Flutter coordinate space). Empty `boxes` means the
/// page has no text layer (scanned page / image book -- OCR selection lands
/// in M5).
///
/// Async: pdfium text traversal is heavyweight and must not block the UI.
Future<CharBoxResult> extractText({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
}) => RustLib.instance.api.crateApiExtractText(bookId: bookId, page: page);

/// List all annotations of a book, ordered by page then creation (FEATURES
/// 4.5.1: the sidebar groups them by page).
Future<List<TextAnnotation>> listAnnotations({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiListAnnotations(bookId: bookId);

/// Create a text-layer annotation (highlight / underline / strikethrough /
/// note). `rects` holds one normalized rect per selected line (FEATURES
/// 4.3.1); `text` is the selected text; `content` the note body (notes only).
Future<AnnotationCreateResult> createAnnotation({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required TextAnnotationKind kind,
  String? text,
  String? content,
  required List<NormRect> rects,
  String? color,
}) => RustLib.instance.api.crateApiCreateAnnotation(
  bookId: bookId,
  page: page,
  kind: kind,
  text: text,
  content: content,
  rects: rects,
  color: color,
);

/// Update a note's body text (FEATURES 4.4.2). Returns 1 on success.
Future<int> updateAnnotationContent({
  required PlatformInt64 annotationId,
  String? content,
}) => RustLib.instance.api.crateApiUpdateAnnotationContent(
  annotationId: annotationId,
  content: content,
);

/// Delete an annotation by id (FEATURES 4.4.2 / 4.5.1). Returns 1 on success.
Future<int> deleteAnnotation({required PlatformInt64 annotationId}) =>
    RustLib.instance.api.crateApiDeleteAnnotation(annotationId: annotationId);

/// Export all annotations of a book as Markdown (FEATURES 4.5.2 / 5.6):
/// `# 阅读标注` -> `## 第 N 页` -> one bullet per annotation, notes quoted
/// underneath; image-layer marks merge into their page sections.
Future<ExportResult> exportAnnotationsMarkdown({
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiExportAnnotationsMarkdown(bookId: bookId);

/// Export all annotations of a book as pretty-printed JSON, including
/// coordinates and style (FEATURES 4.5.3); image-layer marks included (5.6).
Future<ExportResult> exportAnnotationsJson({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiExportAnnotationsJson(bookId: bookId);

/// List all image-layer marks of a book, ordered by page then creation
/// (FEATURES 5.5: the layer panel groups them by page).
Future<List<ImageAnnotation>> listImageAnnotations({
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiListImageAnnotations(bookId: bookId);

/// Create an image-layer mark (brush / shape / sticky / stamp). `payload`
/// and `style` are kind-specific JSON strings (FEATURES 5.1-5.5).
Future<ImageMarkCreateResult> createImageAnnotation({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required ImageAnnotationKind kind,
  required double x,
  required double y,
  double? w,
  double? h,
  required double rotation,
  required String payload,
  required String style,
}) => RustLib.instance.api.crateApiCreateImageAnnotation(
  bookId: bookId,
  page: page,
  kind: kind,
  x: x,
  y: y,
  w: w,
  h: h,
  rotation: rotation,
  payload: payload,
  style: style,
);

/// Update an image-layer mark in full (position / payload / style -- marks
/// are selectable, movable and editable, FEATURES 5.1-5.5). Returns 1 on
/// success.
Future<int> updateImageAnnotation({
  required PlatformInt64 annotationId,
  required double x,
  required double y,
  double? w,
  double? h,
  required double rotation,
  required String payload,
  required String style,
}) => RustLib.instance.api.crateApiUpdateImageAnnotation(
  annotationId: annotationId,
  x: x,
  y: y,
  w: w,
  h: h,
  rotation: rotation,
  payload: payload,
  style: style,
);

/// Delete an image-layer mark by id (FEATURES 5.5: per-mark deletion and
/// layer-wide clear both reduce to this). Returns 1 on success.
Future<int> deleteImageAnnotation({required PlatformInt64 annotationId}) =>
    RustLib.instance.api.crateApiDeleteImageAnnotation(
      annotationId: annotationId,
    );

/// Load the BYOK AI configuration (FEATURES 6.1), or defaults on first run.
/// The built-in text of a role template (设置 → AI 回复): the settings UI
/// shows it when a template is selected so users can read and edit it.
Future<String> templateDefaultText({required String templateId}) =>
    RustLib.instance.api.crateApiTemplateDefaultText(templateId: templateId);

Future<AiConfig> getAiConfig() => RustLib.instance.api.crateApiGetAiConfig();

/// Persist the AI configuration (FEATURES 6.1.1-6.1.5). Returns 1 on success.
Future<int> setAiConfig({required AiConfig config}) =>
    RustLib.instance.api.crateApiSetAiConfig(config: config);

/// List all persisted conversation threads, most recently updated first
/// (FEATURES 6.5.3 / 6.5.4). Empty vec on failure.
Future<List<AiThread>> listAiThreads() =>
    RustLib.instance.api.crateApiListAiThreads();

/// List one thread's messages in conversation order (6.5.4).
Future<List<AiMessage>> listAiMessages({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiListAiMessages(threadId: threadId);

/// Persist a new conversation window; returns its id (-1 on failure).
/// `book_id` binds the window to a book (null = the no-book window); one
/// window per book is enforced by a unique partial index (6.5.4).
Future<AiThreadCreateResult> createAiThread({
  required String title,
  required AiActionType actionType,
  PlatformInt64? bookId,
}) => RustLib.instance.api.crateApiCreateAiThread(
  title: title,
  actionType: actionType,
  bookId: bookId,
);

/// Append a message to a window and bump its `updated_at`; `action_type`
/// (when set) becomes the window's latest action for the history icon.
///
/// `image_png` (vision screenshots, 识图) is written to
/// `{data_dir}/ai_images/{uuid}.png` and its relative path stored on the
/// row, so history reloads can show the capture (v4, FEATURES 6.6.2).
/// Returns 1 on success (0 if the window does not exist).
Future<int> appendAiMessage({
  required PlatformInt64 threadId,
  required AiRole role,
  required String content,
  Uint8List? imagePng,
  AiActionType? actionType,
}) => RustLib.instance.api.crateApiAppendAiMessage(
  threadId: threadId,
  role: role,
  content: content,
  imagePng: imagePng,
  actionType: actionType,
);

/// Delete one conversation window (its messages cascade; their persisted
/// screenshots are removed from disk too). Returns 1 if the window existed,
/// 0 otherwise (6.5.3 per-window deletion).
Future<int> deleteAiThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiDeleteAiThread(threadId: threadId);

/// 6.2). `history` carries the thread's prior turns (6.5.2); the action's
/// system prompt is prepended here. Emits SSE chunks; errors (including
/// "not configured", 10.4) arrive on the stream's error channel.
Stream<String> streamChat({
  required AiActionType action,
  required String text,
  required List<AiMessage> history,
  required bool isFollowUp,
}) => RustLib.instance.api.crateApiStreamChat(
  action: action,
  text: text,
  history: history,
  isFollowUp: isFollowUp,
);

/// Streaming vision analysis of a captured region screenshot (识图, FEATURES
/// 6.6.2 / 7.2): the PNG is sent to the vision model as a data URL and the
/// answer streams back like [stream_chat]. Cancellation is implicit (6.3.2).
/// The screenshot itself is pixel-exact (captured straight from the window's
/// composited layer), so what the model sees is exactly what was selected.
Stream<String> streamVisionPng({required List<int> png}) =>
    RustLib.instance.api.crateApiStreamVisionPng(png: png);

/// Whether a page has a text layer (FEATURES 7.1.2: empty -> scanned /
/// image page). Drives the "扫描识别" prompt in the reader.
Future<bool> pageHasText({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
}) => RustLib.instance.api.crateApiPageHasText(bookId: bookId, page: page);

/// The cached scan result for a page, if any (FEATURES 7.1.4). The Flutter
/// side queries this to build the invisible text layer without re-scanning.
Future<OcrResult?> getPageOcr({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required OcrMode mode,
}) => RustLib.instance.api.crateApiGetPageOcr(
  bookId: bookId,
  page: page,
  mode: mode,
);

/// Apply manual corrections to a page's cached OCR result (FEATURES 7.1.7):
/// replace the text of the edited lines, persist the updated result, and
/// re-index the page so full-text search sees the corrected text (the same
/// incremental-index path scan_page uses). Returns the updated result, or
/// None when the page has no cached scan in [mode].
Future<OcrResult?> updatePageOcrLines({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required OcrMode mode,
  required List<OcrLineEdit> edits,
}) => RustLib.instance.api.crateApiUpdatePageOcrLines(
  bookId: bookId,
  page: page,
  mode: mode,
  edits: edits,
);

/// Full-page OCR scan (FEATURES 7.1.2 / 7.1.8): renders the page at its
/// original resolution (not the display zoom) and runs the engine; the
/// result is cached per (book_id, page, mode) (7.1.4). With the stub engine
/// (models not installed) this returns an explicit error, which the UI
/// surfaces as the "扫描识别" prompt.
///
/// Async: rendering + inference must not block the UI.
Future<ScanPageResult> scanPage({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required OcrMode mode,
}) => RustLib.instance.api.crateApiScanPage(
  bookId: bookId,
  page: page,
  mode: mode,
);

/// Search the whole library's indexed text (FEATURES 3.5.2). Hits are
/// ordered by book then page, capped at [limit] (default 200).
Future<SearchResult> searchBooks({
  required String query,
  PlatformInt64? limit,
}) => RustLib.instance.api.crateApiSearchBooks(query: query, limit: limit);

/// Ensure [book_id]'s pages are indexed (3.5.1 pre-build): triggers a
/// background build when the index is missing (builds run on an independent
/// pdfium document, so they never disturb the reader). Books whose build
/// failed (unreadable file) are not retried until re-imported. Returns
/// nothing -- poll [search_index_status] for progress.
Future<void> ensureBookIndex({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiEnsureBookIndex(bookId: bookId);

/// Index status of a book: "missing" (nothing indexed) | "building"
/// (background build in flight) | "ready" (fully built or has scanned
/// pages) | "failed" (build failed -- unreadable document). Drives the
/// "索引中" badge and the search page footer.
Future<String> searchIndexStatus({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiSearchIndexStatus(bookId: bookId);

/// Paragraphs of one page (1-indexed) for inspection. Extracts on an
/// INDEPENDENT pdfium handle so it never blocks reader rendering (plan §3.0).
/// Scanned pages without a text layer return an empty list (the translate
/// call decides whether to run OCR).
Future<ExtractParagraphsResult> extractPageParagraphs({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
}) => RustLib.instance.api.crateApiExtractPageParagraphs(
  bookId: bookId,
  page: page,
);

/// Reads the cached translation of a page for the CURRENT target language +
/// provider (the cache key is derived from settings, plan §2). A missing row
/// is `translation: None` (not an error). Reading refreshes the LRU access
/// time (plan §7).
Future<PageTranslationResult> getPageTranslation({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
}) =>
    RustLib.instance.api.crateApiGetPageTranslation(bookId: bookId, page: page);

Future<TranslationOverviewResult> getTranslationOverview({
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiGetTranslationOverview(bookId: bookId);

/// Pages of [book_id] with a CURRENT cached translation for the active target
/// language + provider (plan §9). The Dart queue seeds its work list from this
/// single call instead of probing every page (an N+1 of config re-reads).
Future<Int64List> getTranslatedPages({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiGetTranslatedPages(bookId: bookId);

/// Translates one page (1-indexed), streaming progress events (plan §9:
/// the atomic per-page API the Dart queue drives). `force` re-extracts and
/// overwrites the cache even on a hit; the default path returns the cached
/// row instantly.
///
/// Async: extraction + HTTP must not block the UI.
Stream<TranslationProgressEvent> translatePage({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required bool force,
}) => RustLib.instance.api.crateApiTranslatePage(
  bookId: bookId,
  page: page,
  force: force,
);

/// Deletes all cached translations of a book (rows + artifacts, plan §7).
/// Returns 1 on success, 0 on failure.
Future<int> clearTranslations({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiClearTranslations(bookId: bookId);

/// Builds the translated PDF on demand (plan §6), streaming page-granular
/// progress. Final completion is observed by the stream ending; the UI then
/// opens the path from [get_translated_pdf_path]. Errors go to
/// `sink.add_error`.
Stream<TranslationProgressEvent> buildTranslatedPdf({
  required PlatformInt64 bookId,
  required String targetLang,
}) => RustLib.instance.api.crateApiBuildTranslatedPdf(
  bookId: bookId,
  targetLang: targetLang,
);

/// Absolute path the translated PDF for [book_id] + [target_lang] would be
/// (or is) written to; the UI opens it after a build completes.
Future<String> getTranslatedPdfPath({
  required PlatformInt64 bookId,
  required String targetLang,
}) => RustLib.instance.api.crateApiGetTranslatedPdfPath(
  bookId: bookId,
  targetLang: targetLang,
);

/// Renders ONE page's translation as a PDF page bitmap (the bilingual pane's
/// page-level channel, plan §5): the pane displays the translation beside the
/// original page instead of as a text list. Async: building + rasterizing the
/// single-page PDF is CPU/IO work.
Future<TranslatedPageBitmap> renderTranslatedPage({
  required PlatformInt64 bookId,
  required PlatformInt64 page,
  required String targetLang,
  required double dpiScale,
}) => RustLib.instance.api.crateApiRenderTranslatedPage(
  bookId: bookId,
  page: page,
  targetLang: targetLang,
  dpiScale: dpiScale,
);

/// Deletes a book's translated artifacts (PDF + formula images); the cache
/// rows are removed by the FK cascade on book delete. Returns 1 on success.
Future<int> clearTranslationArtifacts({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiClearTranslationArtifacts(bookId: bookId);

/// Reads the translation config (KV `translation_config`, plan §8).
Future<TranslationConfig> getTranslationConfig() =>
    RustLib.instance.api.crateApiGetTranslationConfig();

/// Persists the translation config. Returns 1 on success, 0 on failure.
Future<int> setTranslationConfig({required TranslationConfig config}) =>
    RustLib.instance.api.crateApiSetTranslationConfig(config: config);

/// Registers a book as translating (plan §7 eviction guard: a book in
/// flight is never evicted). Returns 1.
Future<int> startBookTranslation({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiStartBookTranslation(bookId: bookId);

/// Clears the translating registration (task finished / cancelled). Returns 1.
Future<int> cancelTranslation({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiCancelTranslation(bookId: bookId);

Future<GlossaryResult> listTranslationGlossary() =>
    RustLib.instance.api.crateApiListTranslationGlossary();

/// Adds a glossary entry; returns the new id, or -1 on failure.
Future<PlatformInt64> addTranslationGlossary({
  required String sourceTerm,
  required String targetTerm,
  String? sourceLang,
  String? targetLang,
}) => RustLib.instance.api.crateApiAddTranslationGlossary(
  sourceTerm: sourceTerm,
  targetTerm: targetTerm,
  sourceLang: sourceLang,
  targetLang: targetLang,
);

/// Removes a glossary entry; returns 1 on success, 0 if not found.
Future<int> deleteTranslationGlossary({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteTranslationGlossary(id: id);

/// Result of creating a persisted thread (FEATURES 6.5.4). `id` is -1 and
/// `error` set on failure (sentinel convention: no `Result` across FRB).
class AiThreadCreateResult {
  final PlatformInt64 id;
  final String? error;

  const AiThreadCreateResult({required this.id, this.error});

  @override
  int get hashCode => id.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiThreadCreateResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          error == other.error;
}

/// Result of creating an annotation: the new row id, or -1 on error.
class AnnotationCreateResult {
  final PlatformInt64 id;
  final String? error;

  const AnnotationCreateResult({required this.id, this.error});

  @override
  int get hashCode => id.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotationCreateResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          error == other.error;
}

/// Per-character boxes of one page for selection hit-testing (FEATURES 4.1.1).
/// Coordinates are normalized [0,1] with a *top-left* origin (Flutter space).
class CharBoxResult {
  final List<CharBox> boxes;
  final String? error;

  const CharBoxResult({required this.boxes, this.error});

  @override
  int get hashCode => boxes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharBoxResult &&
          runtimeType == other.runtimeType &&
          boxes == other.boxes &&
          error == other.error;
}

/// Text produced by an export command (Markdown / JSON, FEATURES 4.5.2/4.5.3).
class ExportResult {
  final String content;
  final String? error;

  const ExportResult({required this.content, this.error});

  @override
  int get hashCode => content.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportResult &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          error == other.error;
}

/// Result of `extract_page_paragraphs`.
class ExtractParagraphsResult {
  final List<Paragraph> paragraphs;
  final String? error;

  const ExtractParagraphsResult({required this.paragraphs, this.error});

  @override
  int get hashCode => paragraphs.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractParagraphsResult &&
          runtimeType == other.runtimeType &&
          paragraphs == other.paragraphs &&
          error == other.error;
}

/// Glossary entries (plan §4.4).
class GlossaryResult {
  final List<GlossaryEntry> entries;
  final String? error;

  const GlossaryResult({required this.entries, this.error});

  @override
  int get hashCode => entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossaryResult &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          error == other.error;
}

/// Result of creating an image-layer mark: the new row id, or -1 on error.
class ImageMarkCreateResult {
  final PlatformInt64 id;
  final String? error;

  const ImageMarkCreateResult({required this.id, this.error});

  @override
  int get hashCode => id.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageMarkCreateResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          error == other.error;
}

/// Outcome of importing one file (FEATURES 2.1).
class ImportResult {
  /// The imported (or already-existing) book record. `None` on failure.
  final Book? book;

  /// `true` if the original path was already in the library; the existing
  /// record is returned unchanged (de-dup by `original_path`).
  final bool alreadyExisted;

  /// Human-readable error message when import failed; `None` on success.
  final String? error;

  const ImportResult({this.book, required this.alreadyExisted, this.error});

  @override
  int get hashCode => book.hashCode ^ alreadyExisted.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResult &&
          runtimeType == other.runtimeType &&
          book == other.book &&
          alreadyExisted == other.alreadyExisted &&
          error == other.error;
}

/// Result of core initialization, returned to Flutter.
class InitResult {
  final bool ok;

  /// Resolved database file path (for display / diagnostics).
  final String dbPath;

  /// Schema version applied.
  final int schemaVersion;

  /// Human-readable error if initialization failed.
  final String? error;

  const InitResult({
    required this.ok,
    required this.dbPath,
    required this.schemaVersion,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ dbPath.hashCode ^ schemaVersion.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          dbPath == other.dbPath &&
          schemaVersion == other.schemaVersion &&
          error == other.error;
}

/// One manual correction of a recognized line (FEATURES 7.1.7): [line_index]
/// into the cached result's lines, [text] the corrected line text.
class OcrLineEdit {
  final PlatformInt64 lineIndex;
  final String text;

  const OcrLineEdit({required this.lineIndex, required this.text});

  @override
  int get hashCode => lineIndex.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrLineEdit &&
          runtimeType == other.runtimeType &&
          lineIndex == other.lineIndex &&
          text == other.text;
}

/// The OCR mode (FEATURES 7.1.9): high-precision server models by default,
/// fast mobile models switchable in settings.
enum OcrMode {
  highPrecision,
  fast;

  Future<void> asStr() => RustLib.instance.api.crateApiOcrModeAsStr(that: this);
}

/// Result of opening a book for reading.
class OpenBookResult {
  /// Total page count (0 if the document could not be opened).
  final PlatformInt64 pageCount;

  /// Whether the document has a bookmark outline (FEATURES 3.4.2).
  final bool hasOutline;

  /// Error message if opening failed; `None` on success.
  final String? error;

  const OpenBookResult({
    required this.pageCount,
    required this.hasOutline,
    this.error,
  });

  @override
  int get hashCode => pageCount.hashCode ^ hasOutline.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenBookResult &&
          runtimeType == other.runtimeType &&
          pageCount == other.pageCount &&
          hasOutline == other.hasOutline &&
          error == other.error;
}

/// The document outline / table of contents (FEATURES 3.4.2).
class OutlineResult {
  final List<OutlineEntry> entries;
  final String? error;

  const OutlineResult({required this.entries, this.error});

  @override
  int get hashCode => entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutlineResult &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          error == other.error;
}

/// A rendered page bitmap returned to Flutter for texture display (FEATURES 3.6).
class PageRenderResult {
  final int width;
  final int height;

  /// RGBA pixels, row-major, length = width * height * 4.
  final Uint8List rgba;
  final String? error;

  const PageRenderResult({
    required this.width,
    required this.height,
    required this.rgba,
    this.error,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ rgba.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageRenderResult &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba &&
          error == other.error;
}

/// Result of `get_page_translation` / `get_translation_overview`.
class PageTranslationResult {
  /// The cached translation, or None when the page has not been translated.
  final PageTranslation? translation;
  final String? error;

  const PageTranslationResult({this.translation, this.error});

  @override
  int get hashCode => translation.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageTranslationResult &&
          runtimeType == other.runtimeType &&
          translation == other.translation &&
          error == other.error;
}

/// Result of a full-page scan: the recognized lines (empty until the engine
/// is available) + the mode used, or an explicit error.
class ScanPageResult {
  final List<OcrLine> lines;
  final String mode;
  final String? error;

  const ScanPageResult({required this.lines, required this.mode, this.error});

  @override
  int get hashCode => lines.hashCode ^ mode.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanPageResult &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          mode == other.mode &&
          error == other.error;
}

/// One full-text search hit: the book, the 0-indexed page, and a context
/// snippet around the first occurrence of the query.
class SearchHit {
  final PlatformInt64 bookId;
  final PlatformInt64 page;
  final String snippet;

  const SearchHit({
    required this.bookId,
    required this.page,
    required this.snippet,
  });

  @override
  int get hashCode => bookId.hashCode ^ page.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          page == other.page &&
          snippet == other.snippet;
}

/// Result of a library-wide full-text search.
class SearchResult {
  final List<SearchHit> hits;
  final String? error;

  const SearchResult({required this.hits, this.error});

  @override
  int get hashCode => hits.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          hits == other.hits &&
          error == other.error;
}

/// Result of [render_translated_page]: a rendered RGBA page bitmap.
class TranslatedPageBitmap {
  final int width;
  final int height;
  final Uint8List rgba;

  /// Whether the page has a current translation (false -> [rgba] is empty
  /// and the pane shows a "尚未翻译"placeholder).
  final bool hasTranslation;
  final String? error;

  const TranslatedPageBitmap({
    required this.width,
    required this.height,
    required this.rgba,
    required this.hasTranslation,
    this.error,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      rgba.hashCode ^
      hasTranslation.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslatedPageBitmap &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba &&
          hasTranslation == other.hasTranslation &&
          error == other.error;
}

/// Whole-book progress (plan §9): translated pages vs total for the current
/// target language + provider; the Dart queue uses `translated < total` to
/// decide whether to resume.
class TranslationOverviewResult {
  final PlatformInt64 totalPages;
  final PlatformInt64 translatedPages;
  final String targetLang;
  final String? error;

  const TranslationOverviewResult({
    required this.totalPages,
    required this.translatedPages,
    required this.targetLang,
    this.error,
  });

  @override
  int get hashCode =>
      totalPages.hashCode ^
      translatedPages.hashCode ^
      targetLang.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationOverviewResult &&
          runtimeType == other.runtimeType &&
          totalPages == other.totalPages &&
          translatedPages == other.translatedPages &&
          targetLang == other.targetLang &&
          error == other.error;
}
