// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `try_init`

/// Pipeline smoke test. Flutter calls this on startup to confirm the FRB
/// bridge is wired correctly; the UI shows the returned string.
Future<String> ping() => RustLib.instance.api.crateApiPing();

/// Crate version, surfaced in the About / settings UI.
Future<String> appVersion() => RustLib.instance.api.crateApiAppVersion();

/// Initialize the Rust core. Called exactly once on app startup, before any
/// other command. Opens SQLite, applies the schema (idempotent), and sets up
/// tracing. Safe to call again; returns the cached result.
Future<InitResult> initCore() => RustLib.instance.api.crateApiInitCore();

/// Read a setting value by key (skeleton: direct KV read).
/// Returns empty string if the key is absent. Real subsystem repos wrap
/// this in M1; for the skeleton an empty string sentinel is sufficient.
///
/// # Panics
/// Panics if called before `init_core()` (programming error).
Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiGetSetting(key: key);

/// Write a setting value by key (upsert). Skeleton helper for theme etc.
/// Returns 1 on success, 0 on failure.
///
/// # Panics
/// Panics if called before `init_core()` (programming error).
Future<int> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, value: value);

/// Count tables in the DB -- used by the skeleton's diagnostics page to
/// prove the schema was applied. Expects 10 content tables + 1 FTS + version.
///
/// # Panics
/// Panics if called before `init_core()` (programming error).
Future<PlatformInt64> tableCount() => RustLib.instance.api.crateApiTableCount();

/// Result of core initialization, returned to Flutter.
class InitResult {
  final bool ok;

  /// Resolved database file path (for display / diagnostics).
  final String dbPath;

  /// Schema version applied.
  final int schemaVersion;

  /// Human-readable error if initialization failed.
  final String? error;

  const InitResult({
    required this.ok,
    required this.dbPath,
    required this.schemaVersion,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ dbPath.hashCode ^ schemaVersion.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          dbPath == other.dbPath &&
          schemaVersion == other.schemaVersion &&
          error == other.error;
}
