// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One recognized line: normalized rect (top-left origin, Flutter space) +
/// text + confidence. Serialized into `page_ocr_cache.result_json`.
class OcrLine {
  final String text;
  final double x;
  final double y;
  final double w;
  final double h;
  final double confidence;

  const OcrLine({
    required this.text,
    required this.x,
    required this.y,
    required this.w,
    required this.h,
    required this.confidence,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      x.hashCode ^
      y.hashCode ^
      w.hashCode ^
      h.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h &&
          confidence == other.confidence;
}

/// Result of a full-page scan (FEATURES 7.1.3): line boxes + the mode that
/// produced them. The Flutter side turns the lines into an invisible text
/// layer (selection / annotation / AI work on scanned pages).
class OcrResult {
  final List<OcrLine> lines;
  final String mode;

  const OcrResult({required this.lines, required this.mode});

  @override
  int get hashCode => lines.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrResult &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          mode == other.mode;
}
