// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A single character with its normalized page-space bounding box.
///
/// Coordinates are normalized to [0,1] relative to page dimensions, so they
/// remain correct at any zoom. Foundation for precise character-level
/// selection (FEATURES 4.1.1) and text-layer marks (4.3).
class CharBox {
  final String char;
  final double x;
  final double y;
  final double w;
  final double h;

  const CharBox({
    required this.char,
    required this.x,
    required this.y,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode =>
      char.hashCode ^ x.hashCode ^ y.hashCode ^ w.hashCode ^ h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharBox &&
          runtimeType == other.runtimeType &&
          char == other.char &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h;
}

/// A bookmark / outline entry (FEATURES 3.4.2). `page` is 0-indexed; -1 means
/// the destination is not a page (e.g. a URL action).
class OutlineEntry {
  final String title;
  final PlatformInt64 page;
  final List<OutlineEntry> children;

  const OutlineEntry({
    required this.title,
    required this.page,
    required this.children,
  });

  @override
  int get hashCode => title.hashCode ^ page.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutlineEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          page == other.page &&
          children == other.children;
}
